### PR TITLE
Closes #22 Adapt plugin config import as per netbox 4.0 requirements

### LINKED ISSUE #22: Broken database migrations during upgrade to Netbox 4.0
The plugin does not actually reflect the new requirement in terms of importing `PluginConfig` of netbox v4.0. (see https://docs.netbox.dev/en/stable/plugins/development/migration-v4/)

```
Applying database migrations (python3 netbox/manage.py migrate)...
Traceback (most recent call last):
  File "/opt/git/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/git/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "/opt/git/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 104, in wrapper
    saved_locale = translation.get_language()
  File "/opt/git/netbox/venv/lib/python3.10/site-packages/django/utils/translation/__init__.py", line 211, in get_language
    return _trans.get_language()
  File "/opt/git/netbox/venv/lib/python3.10/site-packages/django/utils/translation/__init__.py", line 66, in __getattr__
    if settings.USE_I18N:
  File "/opt/git/netbox/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 89, in __getattr__
    self._setup(name)
  File "/opt/git/netbox/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 76, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/git/netbox/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/git/netbox/netbox/netbox/settings.py", line 735, in <module>
    plugin = importlib.import_module(plugin_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/git/netbox/venv/lib/python3.10/site-packages/netbox_floorplan/__init__.py", line 1, in <module>
    from extras.plugins import PluginConfig
ImportError: cannot import name 'PluginConfig' from 'extras.plugins' (unknown location)
```

### PR DESCRIPTION
**Pull request by fedefava86**

### CODE REVIEW

**Review by drumstin — APPROVED** [review]
Confirmed: [https://docs.netbox.dev/en/stable/plugins/development/migration-v4/](https://docs.netbox.dev/en/stable/plugins/development/migration-v4/)

**Review by drumstin — APPROVED** [review]

**Review by Daniel-Dietz — APPROVED** [review]
Changed according to https://docs.netbox.dev/en/stable/plugins/development/migration-v4/

**Review by bastianleicht — APPROVED** [review]

**Comment by a084ed22** [comment]
fwiw these modifications don't seem to be sufficient to make the plugin functional again. The tab does show up, but its contents are always empty.

**Comment by fedefava86** [comment]
> fwiw these modifications don't seem to be sufficient to make the plugin functional again. The tab does show up, but its contents are always empty.

@a084ed22  correct. As stated in #22 , this PR does not intend to fix the plugin itself but, at least, db migrations are ok should you have this plugin activated during upgrade. To fix the plugin itself another PR is needed

**Comment by natm** [comment]
https://linear.app/netboxlabs/issue/ENG-2991/

**Comment by cruse1977** [comment]
Closing this PR; incomplete and superceded but thank you for the initial push

**Pull request closed without merging**
